import { Container } from "@mui/material";
import { useRouter } from "next/router";
import React from "react";
// images
import p1 from "../../src/assets/img/p1.jpg";
import p1hover from "../../src/assets/img/p1-hover.webp";
import p2 from "../../src/assets/img/p2.webp";
import p2hover from "../../src/assets/img/p2-hover.webp";
import p3 from "../../src/assets/img/p3-hover.webp";
import p4 from "../../src/assets/img/p4-hover.webp";
import p5 from "../../src/assets/img/p5.webp";
import p5hover from "../../src/assets/img/p5-hover.webp";
import ProductCard from "../../components/product-card";

const Collections = () => {
  const products = [
    {
      id: 1,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p1,
      hoverImage: p1hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 2,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      prevPrice: 9123,
      image: p2,
      hoverImage: p2hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 3,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      prevPrice: 11123,
      image: p3,
      hoverImage: p3,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 4,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p4,
      hoverImage: p4,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 5,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p5,
      hoverImage: p5hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 6,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p1,
      hoverImage: p1hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 7,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      prevPrice: 9123,
      image: p2,
      hoverImage: p2hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 8,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      prevPrice: 11123,
      image: p3,
      hoverImage: p3,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 9,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p4,
      hoverImage: p4,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 10,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p5,
      hoverImage: p5hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 11,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p1,
      hoverImage: p1hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 12,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      prevPrice: 9123,
      image: p2,
      hoverImage: p2hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 13,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      prevPrice: 11123,
      image: p3,
      hoverImage: p3,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 14,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p4,
      hoverImage: p4,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 15,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p5,
      hoverImage: p5hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 16,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p1,
      hoverImage: p1hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 17,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      prevPrice: 9123,
      image: p2,
      hoverImage: p2hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 18,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      prevPrice: 11123,
      image: p3,
      hoverImage: p3,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 19,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p4,
      hoverImage: p4,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
    {
      id: 20,
      vendor: "AF",
      code: "AF-123",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["red", "blue", "green", "yellow", "pink"],
      name: "AF Premium SIlber Car Body Cover for Nissan SUNNY",
      details: "package includes: 1pc car body cover, 1pc carry bag, 1pc steel cable, 1pc lock, 1pc antenna patch, 1pc buckle, 1pc warranty card, 1pc manual. 100% waterproof, protects from dust, dents and dings uv ray protection (uv rays cause paint fading). very light and easily handled. matches body profile perfectly. clamp mechanism. elegant silver color. body covers are mainly used to protect two wheelers from weather extremes, fading away from sunlight, scratching etc. they are mainly designed to provide all weather protection to two wheeler body parts. body covers are designed for everyday indoor use, long term storage and outdoor use. features: high quality fabric. water resistant. all weather cover. tie-strap mechanism to hold cover in place. covers entire body of the bike. extremely lightweight and durable. note: do not use the cover on bike which has been recently ridden. this may cause damage to the cover.",
      availability: "In Stock",
      availableQuantity: 10,
      reviews: 4,
      price: 8123,
      image: p5,
      hoverImage: p5hover,
      href: "/products/af-premium-silber-car-body-cover-for-nissan-sunny",
    },
  ];
  // get the slug from the url
  const { slug } = useRouter().query;
  return (
    <div className="collection-page py-10">
      <Container maxWidth="xl">
        <h2 className="text-3xl font-bold mb-5">{slug}</h2>
        <div className="products mt-5 grid xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-3 grid-cols-2 gap-4">
        {products.map((product) => (
          <ProductCard key={product.id} product={product} />
        ))}
      </div>
      </Container>
    </div>
  );
};

export default Collections;
